/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dqs_CONSTANTS_H
#define dqs_CONSTANTS_H

#include "dqs_types.h"



class dqsConstants {
 public:
  dqsConstants();

};

extern const dqsConstants g_dqs_constants;



#endif
