/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dqs_constants.h"



const dqsConstants g_dqs_constants;

dqsConstants::dqsConstants() {
}



